app/models.py
from sqlalchemy import create_engine
from sqlalchemy.orm import scoped_session, sessionmaker
from sqlalchemy.ext.declarative import declarative_base
# from sqlalchemy import Column, Integer, String
# from app import db

engine = create_engine('sqlite:///database.db', echo=True)
db_session = scoped_session(sessionmaker(autocommit=False,
                                         autoflush=False,
                                         bind=engine))
Base = declarative_base()
Base.query = db_session.query_property()

# Set your classes here.

'''
class User(Base):
    __tablename__ = 'Users'

    id = db.Column(db.Integer, primary_key=True)
    name = db.Column(db.String(120), unique=True)
    email = db.Column(db.String(120), unique=True)
    password = db.Column(db.String(30))

    def __init__(self, name=None, password=None):
        self.name = name
        self.password = password
'''

# Create tables.
Base.metadata.create_all(bind=engine)

app/main/forms.py
from flask_wtf import Form
from wtforms import TextField, PasswordField
from wtforms.validators import DataRequired, EqualTo, Length

# Set your classes here.


class RegisterForm(Form):
    name = TextField(
        'Username', validators=[DataRequired(), Length(min=6, max=25)]
    )
    email = TextField(
        'Email', validators=[DataRequired(), Length(min=6, max=40)]
    )
    password = PasswordField(
        'Password', validators=[DataRequired(), Length(min=6, max=40)]
    )
    confirm = PasswordField(
        'Repeat Password',
        [DataRequired(),
        EqualTo('password', message='Passwords must match')]
    )


class LoginForm(Form):
    name = TextField('Username', [DataRequired()])
    password = PasswordField('Password', [DataRequired()])


class ForgotForm(Form):
    email = TextField(
        'Email', validators=[DataRequired(), Length(min=6, max=40)]
    )

app/__init__.py
from flask import Flask
from config import Config
from app.feed.train_center import test_cron, merge_dataset, retrain_model
from apscheduler.schedulers.background import BackgroundScheduler
import atexit

def register_app_blueprints(app):
    print("__init__.py -> register_app_blueprints()")
    from app.main import bp as main_bp
    app.register_blueprint(main_bp)
    
    from app.feed import bp as feed_bp
    app.register_blueprint(feed_bp, url_prefix="/api")


def create_app(config_class=Config):
    print("__init__.py -> create_app()")
    
    sched = BackgroundScheduler(daemon=True)
    sched.add_job(retrain_model,'interval',hours=8)
    sched.start()
    
    #print(sched)
    app = Flask(__name__)
    app.config.from_object(config_class)
    register_app_blueprints(app)
    return app
    
    

app/feed/__init__.py
from flask import Blueprint

bp = Blueprint('feed', __name__)

from app.feed import routes

app/feed/routes.py
from app.feed import bp
from flask import jsonify, request, current_app
from app.feed.fetch_area import main
from app.feed.Predict import vodoo, ConfigureKey
import google.auth.transport.requests
import google.oauth2.id_token
import json

# For authorization
HTTP_REQUEST = google.auth.transport.requests.Request()

@bp.route("/try")
def try_out():
    return jsonify("running version 1.2")

# This is for debugging  
# @bp.route("/find_restaurant/", methods=['GET', 'POST'])
# def find_restaurant():
#     print("routes.py -> find_restaurant()")
#     #coords = request.arg.to_dict() #?x=100&y=200
#     coords = request.get_json()
#     x = coords['x']
#     y = coords['y']
#     user_id = coords['user_id']
#     print("coords:", x, y)
#     new_csv = main(x,y,user_id)
#     ConfigureKey(current_app.config["YELP_API_KEY"])
#     jayson_file = vodoo(new_csv)
#     return jsonify(jayson_file)
#     #return "ok",200

# Main (and only) route
@bp.route("/FEEDME", methods=["GET","POST"])
def FEEDME():
    # Authentication BEGIN
    # From THIS tutorial: https://cloud.google.com/appengine/docs/standard/python/authenticating-users-firebase-appengine
    try : 
        id_token = request.headers["Authorization"].split(' ').pop()
    except KeyError :
        return 'Unauthorized', 401
    try :
        claims = google.oauth2.id_token.verify_firebase_token(
            id_token, HTTP_REQUEST)
    except: 
        return 'Authentication Error', 500
    if not claims:
        return 'Unauthorized', 401
    # Authentication END
    
    arguments = request.args.to_dict()
    
    x = arguments['x']
    y = arguments['y']
    user_id = arguments['uid']
    
    # new_csv = main(40.6942, -73.9866, user_id)
    new_csv = main(x,y,user_id)
    # new_csv = "Alpha.csv"
    
    if (new_csv is None) :
        return jsonify({ "status": 201 }), 201

    jayson_file = vodoo(new_csv, user_id)
    return jsonify(jayson_file), 200
      
@bp.errorhandler(500)
def server_error(e):
    # Log the error and stacktrace.
    print(e)
    return 'An internal error occurred.', 500

app/main/__init__.py
from flask import Blueprint

bp = Blueprint('main', __name__)

from app.main import routes

app/main/routes.py
import os
from flask import render_template, request
from app.main.forms import *
from app.main import bp

'''
@app.teardown_request
def shutdown_session(exception=None):
    db_session.remove()
'''

# Login required decorator.
'''
def login_required(test):
    @wraps(test)
    def wrap(*args, **kwargs):
        if 'logged_in' in session:
            return test(*args, **kwargs)
        else:
            flash('You need to login first.')
            return redirect(url_for('login'))
    return wrap
'''

@bp.route('/')
def home():
    return render_template('pages/placeholder.home.html')


@bp.route('/about')
def about():
    return render_template('pages/placeholder.about.html')

@bp.route('/login')
def login():
    form = LoginForm(request.form)
    return render_template('forms/login.html', form=form)

@bp.route('/register')
def register():
    form = RegisterForm(request.form)
    return render_template('forms/register.html', form=form)

@bp.route('/forgot')
def forgot():
    form = ForgotForm(request.form)
    return render_template('forms/forgot.html', form=form)

@bp.errorhandler(500)
def internal_error(error):
    #db_session.rollback()
    return render_template('errors/500.html'), 500

@bp.errorhandler(404)
def not_found_error(error):
    return render_template('errors/404.html'), 404

app/templates/forms/forgot.html
{% extends 'layouts/form.html' %}
{% block title %}Reset Password{% endblock %}
{% block content %}
  <form method="post" class="form form-reset">
    <h3 class="form-heading">Reset Password <a href="{{ url_for('home') }}" title="Back to homepage"><i class="fa fa-home pull-right"></i></a></h3>
    {{ form.email(class_ = 'form-control first-input last-input', placeholder = form.email.label.text) }}
    <p class="pull-left"><a href="{{ url_for('login') }}">Login</a></p>
    <p class="pull-right"><a href="{{ url_for('register') }}">Register</a></p>
    <input type="submit" value="Submit" class="btn btn-lg btn-primary btn-block" disabled>
    <p>You must add database as well as Flask-Login to enable user management. See the <a href="http://www.realpython.com">Real Python</a> course for more info!</p>
  </form>
{% endblock %}

app/templates/forms/login.html
{% extends 'layouts/form.html' %}
{% block title %}Login{% endblock %}
{% block content %}
  <form method="post" class="form">
    <h3 class="form-heading">Login <a href="{{ url_for('home') }}" title="Back to homepage"><i class="fa fa-home pull-right"></i></a></h3>
    {{ form.name(class_ = 'form-control first-input', placeholder = form.name.label.text, required = true, autofocus = true) }}
    {{ form.password(class_ = 'form-control last-input', placeholder = form.password.label.text, required = true) }}
    <p class="pull-left"><a href="{{ url_for('forgot') }}">Forgot Password?</a></p>
    <p class="pull-right"><a href="{{ url_for('register') }}">Register</a></p>
    <input type="submit" value="Submit" class="btn btn-primary btn-lg btn-block" disabled>
    <p>You must add database as well as Flask-Login to enable user management. See the <a href="http://www.realpython.com">Real Python</a> course for more info!</p>
  </form>
{% endblock %}

app/templates/forms/register.html
{% extends 'layouts/form.html' %}
{% block title %}Register{% endblock %}
{% block content %}
  <form method="post" class="form">
    <h3 class="form-heading">Register <a href="{{ url_for('home') }}" title="Back to homepage"><i class="fa fa-home pull-right"></i></a></h3>
    {{ form.name(class_ = 'form-control first-input', placeholder = form.name.label.text, required = true, autofocus = true) }}
    {{ form.email(class_ = 'form-control', placeholder = form.email.label.text, required = true) }}
    {{ form.password(class_ = 'form-control', placeholder = form.password.label.text, required = true) }}
    {{ form.confirm(class_ = 'form-control last-input', placeholder = form.confirm.label.text, required = true) }}
    <p class="pull-left"><a href="{{ url_for('login') }}">Login</a></p>
    <input type="submit" value="Register" class="btn btn-primary btn-lg btn-block"  disabled>
    <p>You must add database as well as Flask-Login to enable user management. See the <a href="http://www.realpython.com">Real Python</a> course for more info!</p>
  </form>
{% endblock %}

app/templates/layouts/form.html
<!doctype html>
<head>
<meta charset="utf-8">
<title>{% block title %}{% endblock %}</title>

<!-- meta -->
<meta name="description" content="">
<meta name="author" content="">
<meta name="viewport" content="width=device-width,initial-scale=1">
<!-- /meta -->

<!-- styles -->
<link type="text/css" rel="stylesheet" href="/static/css/font-awesome-4.1.0.min.css" />
<link type="text/css" rel="stylesheet" href="/static/css/bootstrap-3.1.1.min.css">
<link type="text/css" rel="stylesheet" href="/static/css/bootstrap-theme-3.1.1.min.css" />
<link type="text/css" rel="stylesheet" href="/static/css/layout.main.css" />
<link type="text/css" rel="stylesheet" href="/static/css/main.css" />
<link type="text/css" rel="stylesheet" href="/static/css/main.responsive.css" />
<link type="text/css" rel="stylesheet" href="/static/css/main.quickfix.css" />
<!-- /styles -->

<!-- favicons -->
<link rel="shortcut icon" href="/static/ico/favicon.png">
<link rel="apple-touch-icon-precomposed" sizes="144x144" href="/static/ico/apple-touch-icon-144-precomposed.png">
<link rel="apple-touch-icon-precomposed" sizes="114x114" href="/static/ico/apple-touch-icon-114-precomposed.png">
<link rel="apple-touch-icon-precomposed" sizes="72x72" href="/static/ico/apple-touch-icon-72-precomposed.png">
<link rel="apple-touch-icon-precomposed" href="/static/ico/apple-touch-icon-57-precomposed.png">
<link rel="shortcut icon" href="/static/ico/favicon.png">
<!-- /favicons -->

<!-- scripts -->
<script src="/static/js/libs/modernizr-2.8.2.min.js"></script>
<!--[if lt IE 9]><script src="/static/js/libs/respond-1.4.2.min.js"></script><![endif]-->
<!-- /scripts -->

</head>
<body class="form-only-page">

  <div class="container">

    {% with messages = get_flashed_messages() %}
      {% if messages %}
        {% for message in messages %}
          <div class="alert alert-warning fade in">
            <a class="close" data-dismiss="alert">&times;</a>
            {{ message }}
          </div>
        {% endfor %}
      {% endif %}
    {% endwith %}

    {% block content %}{% endblock %}

  </div>

  <script type="text/javascript" src="//ajax.googleapis.com/ajax/libs/jquery/1.11.1/jquery.min.js"></script>
  <script>window.jQuery || document.write('<script type="text/javascript" src="/static/js/libs/jquery-1.11.1.min.js"><\/script>')</script>
  <script type="text/javascript" src="/static/js/libs/bootstrap-3.1.1.min.js" defer></script>
  <script type="text/javascript" src="/static/js/plugins.js" defer></script>
  <script type="text/javascript" src="/static/js/script.js" defer></script>
  
  <!-- Google Analytics - Change UA-XXXXX-X to be your site's ID -->
  <script>
  window._gaq = [['_setAccount','UAXXXXXXXX1'],['_trackPageview'],['_trackPageLoadTime']];
  Modernizr.load({
    load: ('https:' == location.protocol ? '//ssl' : '//www') + '.google-analytics.com/ga.js'
  });
  </script>

</body>
</html>

app/templates/layouts/main.html
<!doctype html>
<head>
<meta charset="utf-8">
<title>{% block title %}{% endblock %}</title>

<!-- meta -->
<meta name="description" content="">
<meta name="author" content="">
<meta name="viewport" content="width=device-width,initial-scale=1">
<!-- /meta -->

<!-- styles -->
<link type="text/css" rel="stylesheet" href="/static/css/font-awesome-4.1.0.min.css" />
<link type="text/css" rel="stylesheet" href="/static/css/bootstrap-3.1.1.min.css">
<link type="text/css" rel="stylesheet" href="/static/css/bootstrap-theme-3.1.1.min.css" />
<link type="text/css" rel="stylesheet" href="/static/css/layout.main.css" />
<link type="text/css" rel="stylesheet" href="/static/css/main.css" />
<link type="text/css" rel="stylesheet" href="/static/css/main.responsive.css" />
<link type="text/css" rel="stylesheet" href="/static/css/main.quickfix.css" />
<!-- /styles -->

<!-- favicons -->
<link rel="shortcut icon" href="/static/ico/favicon.png">
<link rel="apple-touch-icon-precomposed" sizes="144x144" href="/static/ico/apple-touch-icon-144-precomposed.png">
<link rel="apple-touch-icon-precomposed" sizes="114x114" href="/static/ico/apple-touch-icon-114-precomposed.png">
<link rel="apple-touch-icon-precomposed" sizes="72x72" href="/static/ico/apple-touch-icon-72-precomposed.png">
<link rel="apple-touch-icon-precomposed" href="/static/ico/apple-touch-icon-57-precomposed.png">
<link rel="shortcut icon" href="/static/ico/favicon.png">
<!-- /favicons -->

<!-- scripts -->
<script src="/static/js/libs/modernizr-2.8.2.min.js"></script>
<!--[if lt IE 9]><script src="/static/js/libs/respond-1.4.2.min.js"></script><![endif]-->
<!-- /scripts -->

</head>
<body>

  <!-- Wrap all page content here -->
  <div id="wrap">

    <!-- Fixed navbar -->
    <div class="navbar navbar-default navbar-fixed-top">
      <div class="container">
        <div class="navbar-header">
          <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
          </button>
          <a class="navbar-brand" href="/">Project name</a>
        </div>
        <div class="collapse navbar-collapse">
          <ul class="nav navbar-nav">
            <li {% if request.endpoint == 'main.home' %} class="active" {% endif %}><a href="{{ url_for('main.home') }}">Home</a></li>
            <li {% if request.endpoint == 'main.about' %} class="active" {% endif %}><a href="{{ url_for('main.about') }}">About</a></li>
            <li class="dropdown">
              <a class="dropdown-toggle" data-toggle="dropdown">Dropdown <b class="caret"></b></a>
              <ul class="dropdown-menu">
                <li><a>Action</a></li>
                <li><a>Another action</a></li>
                <li><a>Something else here</a></li>
                <li class="divider"></li>
                <li class="dropdown-header">Nav header</li>
                <li><a>Separated link</a></li>
                <li><a>One more separated link</a></li>
              </ul>
            </li>
          </ul>
          <ul class="nav navbar-nav pull-right">
            <li><a href="{{ url_for('main.register') }}">Signup</a></li>
            <li><a href="{{ url_for('main.login') }}">Login</a></li>
          </ul>
        </div><!--/.nav-collapse -->
      </div>
    </div>

    <!-- Begin page content -->
    <main id="content" role="main" class="container">

      {% with messages = get_flashed_messages() %}
        {% if messages %}
          {% for message in messages %}
            <div class="alert alert-block alert-error fade in">
              <a class="close" data-dismiss="alert">&times;</a>
              {{ message }}
            </div>
          {% endfor %}
        {% endif %}
      {% endwith %}

      {% block content %}{% endblock %}
      
    </main>

  </div>

  <div id="footer">
    <div class="container">
      <p>Your Company &copy; All Rights Reserved.</p>
      {% block footer %}{% endblock %}
    </div>
  </div>

  <script type="text/javascript" src="//ajax.googleapis.com/ajax/libs/jquery/1.11.1/jquery.min.js"></script>
  <script>window.jQuery || document.write('<script type="text/javascript" src="/static/js/libs/jquery-1.11.1.min.js"><\/script>')</script>
  <script type="text/javascript" src="/static/js/libs/bootstrap-3.1.1.min.js" defer></script>
  <script type="text/javascript" src="/static/js/plugins.js" defer></script>
  <script type="text/javascript" src="/static/js/script.js" defer></script>
  <!-- Google Analytics - Change UA-XXXXX-X to be your site's ID -->
  <script>
  window._gaq = [['_setAccount','UAXXXXXXXX1'],['_trackPageview'],['_trackPageLoadTime']];
  Modernizr.load({
    load: ('https:' == location.protocol ? '//ssl' : '//www') + '.google-analytics.com/ga.js'
  });
  </script>

</body>
</html>

app/templates/pages/placeholder.about.html
{% extends 'layouts/main.html' %}
{% block title %}About{% endblock %}
{% block content %}

<div class="page-header">
  <h1>About Page</h1>
</div>
<p class="lead">This is just a placeholder page which should be replaced with real content.</p>
<p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Ut tellus ligula, imperdiet id lobortis sit amet, scelerisque non sapien. Duis quis dui quis mauris dapibus fringilla. Pellentesque nec tellus ac diam volutpat malesuada.</p>
<p>In quam arcu, interdum vel arcu viverra, vulputate convallis massa. Sed hendrerit velit a arcu euismod, sit amet consequat lacus imperdiet. Nullam quis dui sapien. Vestibulum placerat, justo non fringilla laoreet, dui ipsum posuere nisi, nec vestibulum eros leo ut sapien.</p>
<p>Vivamus eu felis sed magna scelerisque semper in et libero. Curabitur sed convallis odio, quis venenatis sapien. In convallis a velit ac commodo. Donec sapien ligula, vestibulum ut nisi accumsan, facilisis pretium est. Fusce varius semper orci, et egestas nulla cursus a. Phasellus aliquam, mi ac adipiscing lobortis, ipsum augue aliquam ligula, quis fermentum mi augue vel ligula.</p>
<p>Integer elementum malesuada dolor in aliquet.</p>

{% endblock %}

app/templates/pages/placeholder.home.html
{% extends 'layouts/main.html' %}
{% block title %}Home{% endblock %}
{% block content %}

<div class="page-header">
  <h1>Sticky footer with fixed navbar</h1>
</div>
<p class="lead">Pin a fixed-height footer to the bottom of the viewport in desktop browsers with this custom HTML and CSS. A fixed navbar has been added within <code>#wrap</code> with <code>padding-top: 60px;</code> on the <code>.container</code>.</p>

{% endblock %}